### PR TITLE
Merge temp 2

### PR DESCRIPTION
**Pull request by PayamEmami**
This should fix https://github.com/nf-core/metaboigniter/pull/13

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/metaboigniter/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/metaboigniter _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by Leon-Bichmann — COMMENTED** [review]
you still need to remove 'log.info nfcoreHeader()' (line 12) from the main.nf

**Comment by PayamEmami** [comment]
> you still need to remove 'log.info nfcoreHeader()' (line 12) from the main.nf

I just realized that. That's funny that it worked offline. Updated nf-core and nextflow and running again. Will update the PR soon. Thanks for the comment.

**Comment by Leon-Bichmann** [comment]
Also you could append the CHANGELOG that you now updated the template to 1.13.2.

**Comment by PayamEmami** [comment]
> Also you could append the CHANGELOG that you now updated the template to 1.13.2.

Thanks. I think all should be fixed by now.

**Review by Leon-Bichmann — APPROVED** [review]
Good to go from my side then

**Pull request merged**
