### PR TITLE
Removing hashtags

### PR DESCRIPTION
**Pull request by PayamEmami**
Hashtags in the schema were removed

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/metaboigniter/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/metaboigniter _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ewels** [comment]
See discussion in Slack: rather than just removing the headings (hash characters), what did you think about moving the group-level docs into `usage.md`? I fear that most people won’t find it where it is currently, and it’s general enough that it probably warrants having sections under `usage.md`.

**Comment by PayamEmami** [comment]
I have no problems doing this. It was actually like that before! Then we had a discussion to move to the schema! But it's fine with me. I will move it. 


> See discussion in Slack: rather than just removing the headings (hash characters), what did you think about moving the group-level docs into `usage.md`? I fear that most people won’t find it where it is currently, and it’s general enough that it probably warrants having sections under `usage.m

> See discussion in Slack: rather than just removing the headings (hash characters), what did you think about moving the group-level docs into `usage.md`? I fear that most people won’t find it where it is currently, and it’s general enough that it probably warrants having sections under `usage.md`.

**Comment by PayamEmami** [comment]
> See discussion in Slack: rather than just removing the headings (hash characters), what did you think about moving the group-level docs into `usage.md`? I fear that most people won’t find it where it is currently, and it’s general enough that it probably warrants having sections under `usage.md`.

Now the help from the schema is in the usage :)

**Review by Leon-Bichmann — APPROVED** [review]

**Comment by Leon-Bichmann** [comment]
LGTM

**Pull request merged**
